import type { TrendTemplate } from '@/types/discover';

/* ================================================================
   Mock Trend Templates — PRD §3.2 对齐
   每个模板都是一个预设的能力链路 (route: RouteStep[])
   ================================================================ */

export const MOCK_TEMPLATES: TrendTemplate[] = [
  {
    id: 'tpl-001',
    name: '赛博粉发少女',
    category: 'hair',
    thumbnail_url: '/mock/trend-cyber-pink.jpg',
    preview_video_url: '/mock/trend-cyber-pink.mp4',
    usage_count: 52000,
    route: [
      {
        capability: 'hair_color',
        params: { target_color: 'cyber_pink', style: 'vibrant' },
        prompt_template: '将发色变为赛博朋克粉色，{hair_style}保持不变',
        reason: '一键变身粉色系发色',
        estimated_credits: 2,
      },
      {
        capability: 'image_to_video',
        params: { duration: 6 },
        prompt_template: '甩发动作展示新发色变化',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'whip_pan_outfit',
    output_duration: 6,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['hair', 'cyberpunk', 'pink'],
    status: 'published',
    created_at: '2026-02-10',
  },
  {
    id: 'tpl-002',
    name: '日系JK制服',
    category: 'outfit',
    thumbnail_url: '/mock/trend-jk-outfit.jpg',
    preview_video_url: '/mock/trend-jk-outfit.mp4',
    usage_count: 38000,
    route: [
      {
        capability: 'outfit',
        params: { target_outfit: 'jk_uniform', keep_pose: true },
        prompt_template: '换上日系JK校服，保留原有{pose}和表情',
        reason: '经典日系JK校服换装',
        estimated_credits: 3,
      },
      {
        capability: 'image_to_video',
        params: { duration: 8 },
        prompt_template: '旋转展示新穿搭效果',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'spin_occlusion_outfit',
    output_duration: 8,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['outfit', 'jk', 'japanese'],
    status: 'published',
    created_at: '2026-02-09',
  },
  {
    id: 'tpl-003',
    name: '东京街头夜景',
    category: 'scene',
    thumbnail_url: '/mock/trend-tokyo-night.jpg',
    usage_count: 28000,
    route: [
      {
        capability: 'background',
        params: { scene: 'tokyo_night', blend_mode: 'natural' },
        prompt_template: '将背景替换为霓虹灯闪烁的东京街头夜景',
        reason: '营造东京夜景氛围',
        estimated_credits: 3,
      },
      {
        capability: 'lighting',
        params: { direction: 'neon_ambient', intensity: 'medium' },
        prompt_template: '添加霓虹灯环境光映射，使人物融入场景',
        reason: '光线需要匹配新背景',
        estimated_credits: 2,
      },
      {
        capability: 'image_to_video',
        params: { duration: 8 },
        prompt_template: '镜头缓慢推近，霓虹灯闪烁',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'space_warp_outfit',
    output_duration: 8,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['scene', 'tokyo', 'night', 'neon'],
    status: 'published',
    created_at: '2026-02-08',
  },
  {
    id: 'tpl-004',
    name: '电影感冷色调',
    category: 'lighting',
    thumbnail_url: '/mock/trend-cinematic-cold.jpg',
    usage_count: 19000,
    route: [
      {
        capability: 'lighting',
        params: { temperature: 'cold', contrast: 'high', style: 'cinematic' },
        prompt_template: '添加电影级冷色调光影，营造悬疑氛围',
        reason: '打造电影感冷色调',
        estimated_credits: 2,
      },
      {
        capability: 'enhance',
        params: { sharpness: 0.6, film_grain: 0.2 },
        prompt_template: '增加电影胶片质感和细微颗粒',
        estimated_credits: 1,
      },
    ],
    output_duration: 6,
    output_aspect_ratio: '16:9',
    author_type: 'official',
    tags: ['lighting', 'cinematic', 'cold'],
    status: 'published',
    created_at: '2026-02-07',
  },
  {
    id: 'tpl-005',
    name: '水彩画风格',
    category: 'style',
    thumbnail_url: '/mock/trend-watercolor.jpg',
    usage_count: 24000,
    route: [
      {
        capability: 'style_transfer',
        params: { style: 'watercolor', intensity: 0.8 },
        prompt_template: '将照片转换为精美水彩画风格，保留人物轮廓',
        reason: '水彩风格变换',
        estimated_credits: 3,
      },
    ],
    output_duration: 6,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['style', 'watercolor', 'art'],
    status: 'published',
    created_at: '2026-02-07',
  },
  {
    id: 'tpl-006',
    name: '古风汉服变身',
    category: 'mixed',
    thumbnail_url: '/mock/trend-hanfu.jpg',
    preview_video_url: '/mock/trend-hanfu.mp4',
    usage_count: 85000,
    route: [
      {
        capability: 'hair_color',
        params: { target_color: 'black', style: 'classical_updo' },
        prompt_template: '发型变为古典盘发，配以发饰',
        reason: '古风需要对应发型',
        estimated_credits: 2,
      },
      {
        capability: 'outfit',
        params: { target_outfit: 'hanfu_classic', layer: 'full' },
        prompt_template: '换上齐胸襦裙汉服，{color}绣花锦缎',
        reason: '核心变身：换上汉服',
        estimated_credits: 3,
      },
      {
        capability: 'background',
        params: { scene: 'chinese_garden', time: 'spring' },
        prompt_template: '背景替换为春日古典园林，桃花盛开',
        reason: '场景匹配古风主题',
        estimated_credits: 3,
      },
      {
        capability: 'lighting',
        params: { direction: 'soft_ambient', warmth: 0.6 },
        prompt_template: '添加柔和的暖色环境光',
        estimated_credits: 2,
      },
      {
        capability: 'image_to_video',
        params: { duration: 10 },
        prompt_template: '缓慢旋转展示全身古风造型，花瓣飘落',
        estimated_credits: 5,
      },
    ],
    golden_preset: 'spin_occlusion_outfit',
    output_duration: 10,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['mixed', 'hanfu', 'chinese', 'classical'],
    status: 'published',
    created_at: '2026-02-10',
  },
  {
    id: 'tpl-007',
    name: '芭蕾舞姿',
    category: 'action',
    thumbnail_url: '/mock/trend-ballet.jpg',
    usage_count: 15000,
    route: [
      {
        capability: 'action_transfer',
        params: { pose: 'ballet_arabesque', preserve_face: true },
        prompt_template: '将站姿变为优雅的芭蕾舞arabesque姿势',
        reason: '将日常姿势转为芭蕾舞姿',
        estimated_credits: 3,
      },
      {
        capability: 'image_to_video',
        params: { duration: 6 },
        prompt_template: '优雅旋转进入芭蕾姿势',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'spin_occlusion_outfit',
    output_duration: 6,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['action', 'ballet', 'dance'],
    status: 'published',
    created_at: '2026-02-06',
  },
  {
    id: 'tpl-008',
    name: '银灰精灵发',
    category: 'hair',
    thumbnail_url: '/mock/trend-silver-hair.jpg',
    preview_video_url: '/mock/trend-silver-hair.mp4',
    usage_count: 41000,
    route: [
      {
        capability: 'hair_color',
        params: { target_color: 'silver_gray', length: 'long', style: 'flowing' },
        prompt_template: '将发色变为梦幻银灰色长发，精灵风格',
        reason: '银灰长发精灵风',
        estimated_credits: 2,
      },
      {
        capability: 'style_transfer',
        params: { style: 'fantasy_elf', intensity: 0.4 },
        prompt_template: '轻微精灵风格化处理',
        estimated_credits: 2,
      },
      {
        capability: 'image_to_video',
        params: { duration: 6 },
        prompt_template: '微风吹拂银色长发飘动',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'whip_pan_outfit',
    output_duration: 6,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['hair', 'silver', 'elf', 'fantasy'],
    status: 'published',
    created_at: '2026-02-08',
  },
  {
    id: 'tpl-009',
    name: 'Y2K 千禧风穿搭',
    category: 'outfit',
    thumbnail_url: '/mock/trend-y2k.jpg',
    usage_count: 29000,
    route: [
      {
        capability: 'outfit',
        params: { target_outfit: 'y2k_retro', accessories: true },
        prompt_template: '换上Y2K千禧年风格穿搭，低腰裤+亮片上衣',
        reason: 'Y2K复古穿搭变身',
        estimated_credits: 3,
      },
      {
        capability: 'image_to_video',
        params: { duration: 8 },
        prompt_template: '转圈展示Y2K穿搭',
        estimated_credits: 4,
      },
    ],
    golden_preset: 'spin_occlusion_outfit',
    output_duration: 8,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['outfit', 'y2k', 'retro'],
    status: 'published',
    created_at: '2026-02-09',
  },
  {
    id: 'tpl-010',
    name: '金色晚霞光影',
    category: 'lighting',
    thumbnail_url: '/mock/trend-golden-hour.jpg',
    usage_count: 33000,
    route: [
      {
        capability: 'lighting',
        params: { direction: 'golden_hour', intensity: 'strong', warmth: 0.8 },
        prompt_template: '添加温暖的金色夕阳光影效果，轮廓光明显',
        reason: '金色小时光影效果',
        estimated_credits: 2,
      },
    ],
    output_duration: 6,
    output_aspect_ratio: '9:16',
    author_type: 'official',
    tags: ['lighting', 'golden_hour', 'warm'],
    status: 'published',
    created_at: '2026-02-10',
  },
];
